// <auto-generated />
using System;
using FitnessStudioApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessStudioApi.Migrations
{
    [DbContext(typeof(FitnessDbContext))]
    [Migration("20260319174846_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("FitnessStudioApi.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancellationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClassScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WaitlistPosition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassScheduleId");

                    b.HasIndex("MemberId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 1,
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 2,
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 3,
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 2,
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 4,
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 6,
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 1,
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 5,
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 1,
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 4,
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 2,
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 6,
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 7,
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 3,
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 5,
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 1,
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 2,
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 4,
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 6,
                            Status = "Waitlisted",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WaitlistPosition = 1
                        },
                        new
                        {
                            Id = 20,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 3,
                            Status = "Waitlisted",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WaitlistPosition = 2
                        },
                        new
                        {
                            Id = 21,
                            BookingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 7,
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FitnessStudioApi.Models.ClassSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentEnrollment")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstructorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WaitlistCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassTypeId");

                    b.HasIndex("InstructorId");

                    b.ToTable("ClassSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20,
                            ClassTypeId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentEnrollment = 3,
                            EndTime = new DateTime(2025, 7, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            InstructorId = 1,
                            Room = "Studio A",
                            StartTime = new DateTime(2025, 7, 7, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WaitlistCount = 0
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 15,
                            ClassTypeId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentEnrollment = 3,
                            EndTime = new DateTime(2025, 7, 7, 10, 45, 0, 0, DateTimeKind.Utc),
                            InstructorId = 2,
                            Room = "Studio B",
                            StartTime = new DateTime(2025, 7, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WaitlistCount = 0
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 12,
                            ClassTypeId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentEnrollment = 2,
                            EndTime = new DateTime(2025, 7, 8, 7, 45, 0, 0, DateTimeKind.Utc),
                            InstructorId = 2,
                            Room = "Spin Room",
                            StartTime = new DateTime(2025, 7, 8, 7, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WaitlistCount = 0
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 15,
                            ClassTypeId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentEnrollment = 2,
                            EndTime = new DateTime(2025, 7, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            InstructorId = 3,
                            Room = "Studio A",
                            StartTime = new DateTime(2025, 7, 8, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WaitlistCount = 0
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 10,
                            ClassTypeId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentEnrollment = 2,
                            EndTime = new DateTime(2025, 7, 9, 18, 0, 0, 0, DateTimeKind.Utc),
                            InstructorId = 4,
                            Room = "Boxing Ring",
                            StartTime = new DateTime(2025, 7, 9, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WaitlistCount = 0
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 25,
                            ClassTypeId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentEnrollment = 1,
                            EndTime = new DateTime(2025, 7, 9, 19, 30, 0, 0, DateTimeKind.Utc),
                            InstructorId = 1,
                            Room = "Zen Room",
                            StartTime = new DateTime(2025, 7, 9, 19, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WaitlistCount = 0
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 20,
                            ClassTypeId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentEnrollment = 1,
                            EndTime = new DateTime(2025, 7, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            InstructorId = 3,
                            Room = "Studio A",
                            StartTime = new DateTime(2025, 7, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WaitlistCount = 0
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 15,
                            ClassTypeId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentEnrollment = 1,
                            EndTime = new DateTime(2025, 7, 10, 18, 45, 0, 0, DateTimeKind.Utc),
                            InstructorId = 4,
                            Room = "Studio B",
                            StartTime = new DateTime(2025, 7, 10, 18, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WaitlistCount = 0
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 12,
                            ClassTypeId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentEnrollment = 0,
                            EndTime = new DateTime(2025, 7, 11, 7, 45, 0, 0, DateTimeKind.Utc),
                            InstructorId = 2,
                            Room = "Spin Room",
                            StartTime = new DateTime(2025, 7, 11, 7, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WaitlistCount = 0
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 10,
                            ClassTypeId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentEnrollment = 0,
                            EndTime = new DateTime(2025, 7, 11, 18, 0, 0, 0, DateTimeKind.Utc),
                            InstructorId = 4,
                            Room = "Boxing Ring",
                            StartTime = new DateTime(2025, 7, 11, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WaitlistCount = 0
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 3,
                            ClassTypeId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentEnrollment = 3,
                            EndTime = new DateTime(2025, 7, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            InstructorId = 3,
                            Room = "Studio A",
                            StartTime = new DateTime(2025, 7, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WaitlistCount = 2
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 25,
                            ClassTypeId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentEnrollment = 1,
                            EndTime = new DateTime(2025, 7, 12, 19, 30, 0, 0, DateTimeKind.Utc),
                            InstructorId = 1,
                            Room = "Zen Room",
                            StartTime = new DateTime(2025, 7, 12, 19, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WaitlistCount = 0
                        });
                });

            modelBuilder.Entity("FitnessStudioApi.Models.ClassType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CaloriesPerSession")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ClassTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesPerSession = 250,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultCapacity = 20,
                            DefaultDurationMinutes = 60,
                            Description = "Vinyasa flow yoga for flexibility and mindfulness",
                            DifficultyLevel = "AllLevels",
                            IsActive = true,
                            IsPremium = false,
                            Name = "Yoga",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CaloriesPerSession = 500,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultCapacity = 15,
                            DefaultDurationMinutes = 45,
                            Description = "High-intensity interval training for maximum calorie burn",
                            DifficultyLevel = "Intermediate",
                            IsActive = true,
                            IsPremium = false,
                            Name = "HIIT",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CaloriesPerSession = 450,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultCapacity = 12,
                            DefaultDurationMinutes = 45,
                            Description = "Indoor cycling for cardiovascular endurance",
                            DifficultyLevel = "Intermediate",
                            IsActive = true,
                            IsPremium = false,
                            Name = "Spin",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CaloriesPerSession = 300,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultCapacity = 15,
                            DefaultDurationMinutes = 60,
                            Description = "Core strengthening and body alignment",
                            DifficultyLevel = "Beginner",
                            IsActive = true,
                            IsPremium = true,
                            Name = "Pilates",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CaloriesPerSession = 600,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultCapacity = 10,
                            DefaultDurationMinutes = 60,
                            Description = "Boxing fundamentals and cardio boxing workout",
                            DifficultyLevel = "Advanced",
                            IsActive = true,
                            IsPremium = true,
                            Name = "Boxing",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CaloriesPerSession = 50,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultCapacity = 25,
                            DefaultDurationMinutes = 30,
                            Description = "Guided meditation and breathing exercises for stress relief",
                            DifficultyLevel = "Beginner",
                            IsActive = true,
                            IsPremium = false,
                            Name = "Meditation",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FitnessStudioApi.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specializations")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Certified yoga instructor with 10 years of experience",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sarah.kim@zenithfitness.com",
                            FirstName = "Sarah",
                            HireDate = new DateOnly(2020, 1, 15),
                            IsActive = true,
                            LastName = "Kim",
                            Phone = "555-1001",
                            Specializations = "Yoga,Pilates,Meditation",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Former competitive athlete specializing in high-intensity training",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mike.torres@zenithfitness.com",
                            FirstName = "Mike",
                            HireDate = new DateOnly(2021, 3, 1),
                            IsActive = true,
                            LastName = "Torres",
                            Phone = "555-1002",
                            Specializations = "HIIT,Boxing,Spin",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Pilates and mindfulness expert with a holistic approach",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "priya.patel@zenithfitness.com",
                            FirstName = "Priya",
                            HireDate = new DateOnly(2022, 6, 15),
                            IsActive = true,
                            LastName = "Patel",
                            Phone = "555-1003",
                            Specializations = "Pilates,Yoga,Meditation",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Professional boxing coach and strength training specialist",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david.okonkwo@zenithfitness.com",
                            FirstName = "David",
                            HireDate = new DateOnly(2023, 1, 10),
                            IsActive = true,
                            LastName = "Okonkwo",
                            Phone = "555-1004",
                            Specializations = "Boxing,HIIT,Spin",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FitnessStudioApi.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1990, 3, 15),
                            Email = "alice.johnson@email.com",
                            EmergencyContactName = "Bob Johnson",
                            EmergencyContactPhone = "555-0102",
                            FirstName = "Alice",
                            IsActive = true,
                            JoinDate = new DateOnly(2024, 6, 1),
                            LastName = "Johnson",
                            Phone = "555-0101",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1985, 7, 22),
                            Email = "marcus.chen@email.com",
                            EmergencyContactName = "Li Chen",
                            EmergencyContactPhone = "555-0202",
                            FirstName = "Marcus",
                            IsActive = true,
                            JoinDate = new DateOnly(2024, 7, 15),
                            LastName = "Chen",
                            Phone = "555-0201",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1992, 11, 8),
                            Email = "sophia.martinez@email.com",
                            EmergencyContactName = "Carlos Martinez",
                            EmergencyContactPhone = "555-0302",
                            FirstName = "Sophia",
                            IsActive = true,
                            JoinDate = new DateOnly(2024, 8, 1),
                            LastName = "Martinez",
                            Phone = "555-0301",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1988, 1, 30),
                            Email = "james.williams@email.com",
                            EmergencyContactName = "Sarah Williams",
                            EmergencyContactPhone = "555-0402",
                            FirstName = "James",
                            IsActive = true,
                            JoinDate = new DateOnly(2024, 5, 1),
                            LastName = "Williams",
                            Phone = "555-0401",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1995, 5, 12),
                            Email = "emma.davis@email.com",
                            EmergencyContactName = "Tom Davis",
                            EmergencyContactPhone = "555-0502",
                            FirstName = "Emma",
                            IsActive = true,
                            JoinDate = new DateOnly(2024, 9, 1),
                            LastName = "Davis",
                            Phone = "555-0501",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1993, 9, 25),
                            Email = "daniel.brown@email.com",
                            EmergencyContactName = "Lisa Brown",
                            EmergencyContactPhone = "555-0602",
                            FirstName = "Daniel",
                            IsActive = true,
                            JoinDate = new DateOnly(2024, 4, 15),
                            LastName = "Brown",
                            Phone = "555-0601",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2000, 2, 14),
                            Email = "olivia.wilson@email.com",
                            EmergencyContactName = "Mark Wilson",
                            EmergencyContactPhone = "555-0702",
                            FirstName = "Olivia",
                            IsActive = true,
                            JoinDate = new DateOnly(2024, 10, 1),
                            LastName = "Wilson",
                            Phone = "555-0701",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1987, 12, 3),
                            Email = "ryan.taylor@email.com",
                            EmergencyContactName = "Karen Taylor",
                            EmergencyContactPhone = "555-0802",
                            FirstName = "Ryan",
                            IsActive = false,
                            JoinDate = new DateOnly(2024, 3, 1),
                            LastName = "Taylor",
                            Phone = "555-0801",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FitnessStudioApi.Models.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FreezeEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FreezeStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MembershipPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("MembershipPlanId");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2025, 7, 1),
                            MemberId = 1,
                            MembershipPlanId = 2,
                            PaymentStatus = "Paid",
                            StartDate = new DateOnly(2025, 6, 1),
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2025, 7, 1),
                            MemberId = 2,
                            MembershipPlanId = 3,
                            PaymentStatus = "Paid",
                            StartDate = new DateOnly(2025, 6, 1),
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2025, 7, 1),
                            MemberId = 3,
                            MembershipPlanId = 1,
                            PaymentStatus = "Paid",
                            StartDate = new DateOnly(2025, 6, 1),
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2025, 7, 1),
                            MemberId = 4,
                            MembershipPlanId = 2,
                            PaymentStatus = "Paid",
                            StartDate = new DateOnly(2025, 6, 1),
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2025, 7, 1),
                            MemberId = 5,
                            MembershipPlanId = 1,
                            PaymentStatus = "Paid",
                            StartDate = new DateOnly(2025, 6, 1),
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2025, 7, 1),
                            MemberId = 6,
                            MembershipPlanId = 3,
                            PaymentStatus = "Paid",
                            StartDate = new DateOnly(2025, 6, 1),
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2024, 7, 1),
                            MemberId = 1,
                            MembershipPlanId = 1,
                            PaymentStatus = "Paid",
                            StartDate = new DateOnly(2024, 6, 1),
                            Status = "Expired",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2024, 4, 1),
                            MemberId = 8,
                            MembershipPlanId = 1,
                            PaymentStatus = "Refunded",
                            StartDate = new DateOnly(2024, 3, 1),
                            Status = "Cancelled",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FitnessStudioApi.Models.MembershipPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowsPremiumClasses")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxClassBookingsPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MembershipPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowsPremiumClasses = false,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Access to standard classes, 3 bookings per week",
                            DurationMonths = 1,
                            IsActive = true,
                            MaxClassBookingsPerWeek = 3,
                            Name = "Basic",
                            Price = 29.99m,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AllowsPremiumClasses = true,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Access to all classes including premium, 5 bookings per week",
                            DurationMonths = 1,
                            IsActive = true,
                            MaxClassBookingsPerWeek = 5,
                            Name = "Premium",
                            Price = 49.99m,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AllowsPremiumClasses = true,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Unlimited access to all classes and premium features",
                            DurationMonths = 1,
                            IsActive = true,
                            MaxClassBookingsPerWeek = -1,
                            Name = "Elite",
                            Price = 79.99m,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FitnessStudioApi.Models.Booking", b =>
                {
                    b.HasOne("FitnessStudioApi.Models.ClassSchedule", "ClassSchedule")
                        .WithMany("Bookings")
                        .HasForeignKey("ClassScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessStudioApi.Models.Member", "Member")
                        .WithMany("Bookings")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassSchedule");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FitnessStudioApi.Models.ClassSchedule", b =>
                {
                    b.HasOne("FitnessStudioApi.Models.ClassType", "ClassType")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("ClassTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessStudioApi.Models.Instructor", "Instructor")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassType");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("FitnessStudioApi.Models.Membership", b =>
                {
                    b.HasOne("FitnessStudioApi.Models.Member", "Member")
                        .WithMany("Memberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessStudioApi.Models.MembershipPlan", "MembershipPlan")
                        .WithMany("Memberships")
                        .HasForeignKey("MembershipPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("MembershipPlan");
                });

            modelBuilder.Entity("FitnessStudioApi.Models.ClassSchedule", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("FitnessStudioApi.Models.ClassType", b =>
                {
                    b.Navigation("ClassSchedules");
                });

            modelBuilder.Entity("FitnessStudioApi.Models.Instructor", b =>
                {
                    b.Navigation("ClassSchedules");
                });

            modelBuilder.Entity("FitnessStudioApi.Models.Member", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("FitnessStudioApi.Models.MembershipPlan", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
