// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VetClinicApi.Data;

#nullable disable

namespace VetClinicApi.Migrations
{
    [DbContext(typeof(VetClinicDbContext))]
    partial class VetClinicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("VetClinicApi.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(30);

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VeterinarianId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("VeterinarianId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2025, 1, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 30,
                            Notes = "All good",
                            PetId = 1,
                            Reason = "Annual checkup",
                            Status = "Completed",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            VeterinarianId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2025, 1, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 30,
                            PetId = 2,
                            Reason = "Vaccination update",
                            Status = "Completed",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            VeterinarianId = 1
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2025, 1, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 60,
                            PetId = 3,
                            Reason = "Limping on right front leg",
                            Status = "Completed",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            VeterinarianId = 2
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2025, 1, 13, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 30,
                            PetId = 4,
                            Reason = "Skin irritation",
                            Status = "Completed",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            VeterinarianId = 1
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDate = new DateTime(2025, 1, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            CancellationReason = "Owner rescheduled",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 30,
                            PetId = 5,
                            Reason = "Dental cleaning",
                            Status = "Cancelled",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            VeterinarianId = 2
                        },
                        new
                        {
                            Id = 6,
                            AppointmentDate = new DateTime(2025, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 30,
                            PetId = 1,
                            Reason = "Follow-up visit",
                            Status = "Scheduled",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            VeterinarianId = 1
                        },
                        new
                        {
                            Id = 7,
                            AppointmentDate = new DateTime(2025, 2, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 45,
                            PetId = 6,
                            Reason = "Wing clipping and checkup",
                            Status = "Scheduled",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            VeterinarianId = 3
                        },
                        new
                        {
                            Id = 8,
                            AppointmentDate = new DateTime(2025, 2, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 30,
                            PetId = 7,
                            Reason = "Nail trimming",
                            Status = "Scheduled",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            VeterinarianId = 3
                        },
                        new
                        {
                            Id = 9,
                            AppointmentDate = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 30,
                            PetId = 3,
                            Reason = "Post-surgery follow-up",
                            Status = "CheckedIn",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            VeterinarianId = 2
                        },
                        new
                        {
                            Id = 10,
                            AppointmentDate = new DateTime(2025, 1, 8, 15, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 30,
                            PetId = 5,
                            Reason = "Routine vaccination",
                            Status = "NoShow",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            VeterinarianId = 1
                        });
                });

            modelBuilder.Entity("VetClinicApi.Models.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FollowUpDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("VeterinarianId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("PetId");

                    b.HasIndex("VeterinarianId");

                    b.ToTable("MedicalRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Diagnosis = "Healthy - no issues found",
                            FollowUpDate = new DateOnly(2026, 1, 10),
                            Notes = "Weight is ideal. Teeth in good condition.",
                            PetId = 1,
                            Treatment = "No treatment needed. Continue current diet and exercise.",
                            VeterinarianId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 2,
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Diagnosis = "Due for FVRCP booster",
                            Notes = "Cat was calm during procedure.",
                            PetId = 2,
                            Treatment = "Administered FVRCP vaccine booster.",
                            VeterinarianId = 1
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 3,
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Diagnosis = "Mild sprain in right front leg",
                            FollowUpDate = new DateOnly(2025, 1, 26),
                            Notes = "X-ray showed no fracture.",
                            PetId = 3,
                            Treatment = "Rest for 2 weeks. Anti-inflammatory medication prescribed.",
                            VeterinarianId = 2
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 4,
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Diagnosis = "Allergic dermatitis",
                            FollowUpDate = new DateOnly(2025, 2, 13),
                            Notes = "Likely food allergy. Trial elimination diet.",
                            PetId = 4,
                            Treatment = "Topical corticosteroid cream. Dietary adjustment recommended.",
                            VeterinarianId = 1
                        });
                });

            modelBuilder.Entity("VetClinicApi.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Oak Street",
                            City = "Springfield",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sarah.johnson@email.com",
                            FirstName = "Sarah",
                            LastName = "Johnson",
                            Phone = "555-0101",
                            State = "IL",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            ZipCode = "62701"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Maple Ave",
                            City = "Portland",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "michael.chen@email.com",
                            FirstName = "Michael",
                            LastName = "Chen",
                            Phone = "555-0102",
                            State = "OR",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            ZipCode = "97201"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine Road",
                            City = "Austin",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "emily.rodriguez@email.com",
                            FirstName = "Emily",
                            LastName = "Rodriguez",
                            Phone = "555-0103",
                            State = "TX",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            ZipCode = "73301"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Elm Blvd",
                            City = "Seattle",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david.kim@email.com",
                            FirstName = "David",
                            LastName = "Kim",
                            Phone = "555-0104",
                            State = "WA",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            ZipCode = "98101"
                        },
                        new
                        {
                            Id = 5,
                            Address = "654 Cedar Lane",
                            City = "Denver",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jessica.taylor@email.com",
                            FirstName = "Jessica",
                            LastName = "Taylor",
                            Phone = "555-0105",
                            State = "CO",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            ZipCode = "80201"
                        });
                });

            modelBuilder.Entity("VetClinicApi.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("MicrochipNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MicrochipNumber")
                        .IsUnique()
                        .HasFilter("[MicrochipNumber] IS NOT NULL");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breed = "Golden Retriever",
                            Color = "Golden",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2020, 3, 15),
                            IsActive = true,
                            MicrochipNumber = "MC-001-2020",
                            Name = "Buddy",
                            OwnerId = 1,
                            Species = "Dog",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Weight = 32.5m
                        },
                        new
                        {
                            Id = 2,
                            Breed = "Siamese",
                            Color = "Cream",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2019, 7, 22),
                            IsActive = true,
                            MicrochipNumber = "MC-002-2019",
                            Name = "Whiskers",
                            OwnerId = 1,
                            Species = "Cat",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Weight = 4.8m
                        },
                        new
                        {
                            Id = 3,
                            Breed = "German Shepherd",
                            Color = "Black and Tan",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2021, 1, 10),
                            IsActive = true,
                            MicrochipNumber = "MC-003-2021",
                            Name = "Max",
                            OwnerId = 2,
                            Species = "Dog",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Weight = 38.0m
                        },
                        new
                        {
                            Id = 4,
                            Breed = "Maine Coon",
                            Color = "Tabby",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2022, 5, 8),
                            IsActive = true,
                            MicrochipNumber = "MC-004-2022",
                            Name = "Luna",
                            OwnerId = 3,
                            Species = "Cat",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Weight = 6.2m
                        },
                        new
                        {
                            Id = 5,
                            Breed = "Beagle",
                            Color = "Tricolor",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2020, 11, 30),
                            IsActive = true,
                            MicrochipNumber = "MC-005-2020",
                            Name = "Charlie",
                            OwnerId = 3,
                            Species = "Dog",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Weight = 12.5m
                        },
                        new
                        {
                            Id = 6,
                            Breed = "Cockatiel",
                            Color = "Yellow",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2023, 2, 14),
                            IsActive = true,
                            Name = "Tweety",
                            OwnerId = 4,
                            Species = "Bird",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Weight = 0.09m
                        },
                        new
                        {
                            Id = 7,
                            Breed = "Holland Lop",
                            Color = "White",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2023, 6, 20),
                            IsActive = true,
                            MicrochipNumber = "MC-007-2023",
                            Name = "Thumper",
                            OwnerId = 5,
                            Species = "Rabbit",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Weight = 1.8m
                        },
                        new
                        {
                            Id = 8,
                            Breed = "Bombay",
                            Color = "Black",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2018, 9, 3),
                            IsActive = false,
                            MicrochipNumber = "MC-008-2018",
                            Name = "Shadow",
                            OwnerId = 4,
                            Species = "Cat",
                            UpdatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Weight = 5.1m
                        });
                });

            modelBuilder.Entity("VetClinicApi.Models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Dosage = "25mg twice daily",
                            DurationDays = 14,
                            EndDate = new DateOnly(2025, 1, 26),
                            Instructions = "Give with food. Monitor for stomach upset.",
                            MedicalRecordId = 3,
                            MedicationName = "Carprofen",
                            StartDate = new DateOnly(2025, 1, 12)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Dosage = "Apply thin layer twice daily",
                            DurationDays = 21,
                            EndDate = new DateOnly(2025, 2, 3),
                            Instructions = "Apply to affected areas. Prevent licking with cone if needed.",
                            MedicalRecordId = 4,
                            MedicationName = "Hydrocortisone Cream",
                            StartDate = new DateOnly(2025, 1, 13)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Dosage = "50mg as needed",
                            DurationDays = 7,
                            EndDate = new DateOnly(2025, 1, 19),
                            Instructions = "Only if showing signs of significant pain.",
                            MedicalRecordId = 3,
                            MedicationName = "Tramadol",
                            StartDate = new DateOnly(2025, 1, 12)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Dosage = "1 capsule daily",
                            DurationDays = 90,
                            EndDate = new DateOnly(2025, 4, 13),
                            Instructions = "Mix with food. Supports skin health.",
                            MedicalRecordId = 4,
                            MedicationName = "Omega-3 Fish Oil",
                            StartDate = new DateOnly(2025, 1, 13)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Dosage = "1 tablet monthly",
                            DurationDays = 365,
                            EndDate = new DateOnly(2026, 1, 10),
                            Instructions = "Give on the same day each month with a meal.",
                            MedicalRecordId = 1,
                            MedicationName = "Heartworm Prevention",
                            StartDate = new DateOnly(2025, 1, 10)
                        });
                });

            modelBuilder.Entity("VetClinicApi.Models.Vaccination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdministeredByVetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateAdministered")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VaccineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdministeredByVetId");

                    b.HasIndex("PetId");

                    b.ToTable("Vaccinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdministeredByVetId = 1,
                            BatchNumber = "RAB-2024-1001",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DateAdministered = new DateOnly(2024, 3, 15),
                            ExpirationDate = new DateOnly(2027, 3, 15),
                            Notes = "3-year rabies vaccine",
                            PetId = 1,
                            VaccineName = "Rabies"
                        },
                        new
                        {
                            Id = 2,
                            AdministeredByVetId = 1,
                            BatchNumber = "DHPP-2024-2001",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DateAdministered = new DateOnly(2024, 3, 15),
                            ExpirationDate = new DateOnly(2025, 3, 15),
                            Notes = "Annual booster",
                            PetId = 1,
                            VaccineName = "DHPP"
                        },
                        new
                        {
                            Id = 3,
                            AdministeredByVetId = 1,
                            BatchNumber = "FVRCP-2025-3001",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DateAdministered = new DateOnly(2025, 1, 10),
                            ExpirationDate = new DateOnly(2026, 1, 10),
                            PetId = 2,
                            VaccineName = "FVRCP"
                        },
                        new
                        {
                            Id = 4,
                            AdministeredByVetId = 2,
                            BatchNumber = "RAB-2023-4001",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DateAdministered = new DateOnly(2023, 6, 1),
                            ExpirationDate = new DateOnly(2024, 6, 1),
                            Notes = "1-year rabies vaccine - EXPIRED",
                            PetId = 3,
                            VaccineName = "Rabies"
                        },
                        new
                        {
                            Id = 5,
                            AdministeredByVetId = 2,
                            BatchNumber = "DHPP-2024-5001",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DateAdministered = new DateOnly(2024, 6, 15),
                            ExpirationDate = new DateOnly(2025, 2, 15),
                            Notes = "Expiring soon",
                            PetId = 5,
                            VaccineName = "DHPP"
                        },
                        new
                        {
                            Id = 6,
                            AdministeredByVetId = 3,
                            BatchNumber = "RHDV-2024-6001",
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DateAdministered = new DateOnly(2024, 8, 20),
                            ExpirationDate = new DateOnly(2025, 8, 20),
                            Notes = "Rabbit hemorrhagic disease vaccine",
                            PetId = 7,
                            VaccineName = "RHDV2"
                        });
                });

            modelBuilder.Entity("VetClinicApi.Models.Veterinarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialization")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.ToTable("Veterinarians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "amanda.foster@happypaws.com",
                            FirstName = "Dr. Amanda",
                            HireDate = new DateOnly(2015, 6, 1),
                            IsAvailable = true,
                            LastName = "Foster",
                            LicenseNumber = "VET-2015-001",
                            Phone = "555-0201",
                            Specialization = "Small Animals"
                        },
                        new
                        {
                            Id = 2,
                            Email = "robert.martinez@happypaws.com",
                            FirstName = "Dr. Robert",
                            HireDate = new DateOnly(2018, 3, 15),
                            IsAvailable = true,
                            LastName = "Martinez",
                            LicenseNumber = "VET-2018-002",
                            Phone = "555-0202",
                            Specialization = "Surgery"
                        },
                        new
                        {
                            Id = 3,
                            Email = "lisa.park@happypaws.com",
                            FirstName = "Dr. Lisa",
                            HireDate = new DateOnly(2020, 9, 1),
                            IsAvailable = false,
                            LastName = "Park",
                            LicenseNumber = "VET-2020-003",
                            Phone = "555-0203",
                            Specialization = "Exotic Animals"
                        });
                });

            modelBuilder.Entity("VetClinicApi.Models.Appointment", b =>
                {
                    b.HasOne("VetClinicApi.Models.Pet", "Pet")
                        .WithMany("Appointments")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetClinicApi.Models.Veterinarian", "Veterinarian")
                        .WithMany("Appointments")
                        .HasForeignKey("VeterinarianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("VetClinicApi.Models.MedicalRecord", b =>
                {
                    b.HasOne("VetClinicApi.Models.Appointment", "Appointment")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("VetClinicApi.Models.MedicalRecord", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetClinicApi.Models.Pet", "Pet")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetClinicApi.Models.Veterinarian", "Veterinarian")
                        .WithMany()
                        .HasForeignKey("VeterinarianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Pet");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("VetClinicApi.Models.Pet", b =>
                {
                    b.HasOne("VetClinicApi.Models.Owner", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("VetClinicApi.Models.Prescription", b =>
                {
                    b.HasOne("VetClinicApi.Models.MedicalRecord", "MedicalRecord")
                        .WithMany("Prescriptions")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("VetClinicApi.Models.Vaccination", b =>
                {
                    b.HasOne("VetClinicApi.Models.Veterinarian", "AdministeredByVet")
                        .WithMany()
                        .HasForeignKey("AdministeredByVetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetClinicApi.Models.Pet", "Pet")
                        .WithMany("Vaccinations")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdministeredByVet");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("VetClinicApi.Models.Appointment", b =>
                {
                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("VetClinicApi.Models.MedicalRecord", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("VetClinicApi.Models.Owner", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("VetClinicApi.Models.Pet", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");

                    b.Navigation("Vaccinations");
                });

            modelBuilder.Entity("VetClinicApi.Models.Veterinarian", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
