// <auto-generated />
using System;
using LibraryApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryApi.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("LibraryApi.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biography")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "American novelist known for To Kill a Mockingbird.",
                            BirthDate = new DateOnly(1926, 4, 28),
                            Country = "United States",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Harper",
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "English novelist and essayist, known for 1984 and Animal Farm.",
                            BirthDate = new DateOnly(1903, 6, 25),
                            Country = "United Kingdom",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "George",
                            LastName = "Orwell"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "American author and biochemistry professor, prolific science fiction writer.",
                            BirthDate = new DateOnly(1920, 1, 2),
                            Country = "United States",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Isaac",
                            LastName = "Asimov"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Israeli historian and author of Sapiens and Homo Deus.",
                            BirthDate = new DateOnly(1976, 2, 24),
                            Country = "Israel",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Yuval Noah",
                            LastName = "Harari"
                        },
                        new
                        {
                            Id = 5,
                            Biography = "American journalist and biographer.",
                            BirthDate = new DateOnly(1952, 5, 20),
                            Country = "United States",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Walter",
                            LastName = "Isaacson"
                        },
                        new
                        {
                            Id = 6,
                            Biography = "English novelist known for Pride and Prejudice and other classic works.",
                            BirthDate = new DateOnly(1775, 12, 16),
                            Country = "United Kingdom",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Jane",
                            LastName = "Austen"
                        });
                });

            modelBuilder.Entity("LibraryApi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("English");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableCopies = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A novel about racial injustice in the American South.",
                            ISBN = "978-0-06-112008-4",
                            Language = "English",
                            PageCount = 281,
                            PublicationYear = 1960,
                            Publisher = "J.B. Lippincott & Co.",
                            Title = "To Kill a Mockingbird",
                            TotalCopies = 3,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AvailableCopies = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A dystopian novel set in a totalitarian society.",
                            ISBN = "978-0-452-28423-4",
                            Language = "English",
                            PageCount = 328,
                            PublicationYear = 1949,
                            Publisher = "Secker & Warburg",
                            Title = "1984",
                            TotalCopies = 4,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AvailableCopies = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An allegorical novella about a group of farm animals.",
                            ISBN = "978-0-452-28424-1",
                            Language = "English",
                            PageCount = 112,
                            PublicationYear = 1945,
                            Publisher = "Secker & Warburg",
                            Title = "Animal Farm",
                            TotalCopies = 2,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AvailableCopies = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The first novel in Asimov's Foundation series.",
                            ISBN = "978-0-553-29335-7",
                            Language = "English",
                            PageCount = 244,
                            PublicationYear = 1951,
                            Publisher = "Gnome Press",
                            Title = "Foundation",
                            TotalCopies = 3,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AvailableCopies = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A collection of nine science fiction short stories.",
                            ISBN = "978-0-553-29438-5",
                            Language = "English",
                            PageCount = 253,
                            PublicationYear = 1950,
                            Publisher = "Gnome Press",
                            Title = "I, Robot",
                            TotalCopies = 2,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            AvailableCopies = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A narrative history of humankind from the Stone Age to the present.",
                            ISBN = "978-0-06-231609-7",
                            Language = "English",
                            PageCount = 443,
                            PublicationYear = 2011,
                            Publisher = "Harper",
                            Title = "Sapiens: A Brief History of Humankind",
                            TotalCopies = 5,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            AvailableCopies = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An exploration of humanity's future.",
                            ISBN = "978-0-06-246431-6",
                            Language = "English",
                            PageCount = 450,
                            PublicationYear = 2015,
                            Publisher = "Harper",
                            Title = "Homo Deus: A Brief History of Tomorrow",
                            TotalCopies = 3,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            AvailableCopies = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The authorized biography of Apple co-founder Steve Jobs.",
                            ISBN = "978-1-4516-4853-9",
                            Language = "English",
                            PageCount = 656,
                            PublicationYear = 2011,
                            Publisher = "Simon & Schuster",
                            Title = "Steve Jobs",
                            TotalCopies = 4,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            AvailableCopies = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A classic novel of manners set in Georgian England.",
                            ISBN = "978-0-14-143951-8",
                            Language = "English",
                            PageCount = 432,
                            PublicationYear = 1813,
                            Publisher = "T. Egerton",
                            Title = "Pride and Prejudice",
                            TotalCopies = 3,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            AvailableCopies = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A novel about the Dashwood sisters and their romantic pursuits.",
                            ISBN = "978-0-14-143966-2",
                            Language = "English",
                            PageCount = 409,
                            PublicationYear = 1811,
                            Publisher = "T. Egerton",
                            Title = "Sense and Sensibility",
                            TotalCopies = 2,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            AvailableCopies = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A science fiction detective novel featuring robot R. Daneel Olivaw.",
                            ISBN = "978-0-553-29340-1",
                            Language = "English",
                            PageCount = 206,
                            PublicationYear = 1954,
                            Publisher = "Doubleday",
                            Title = "The Caves of Steel",
                            TotalCopies = 2,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            AvailableCopies = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Explores the biggest questions facing humanity today.",
                            ISBN = "978-0-525-51217-2",
                            Language = "English",
                            PageCount = 372,
                            PublicationYear = 2018,
                            Publisher = "Spiegel & Grau",
                            Title = "21 Lessons for the 21st Century",
                            TotalCopies = 3,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LibraryApi.Models.BookAuthor", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 3
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 3
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 5
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 6
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 6
                        },
                        new
                        {
                            BookId = 11,
                            AuthorId = 3
                        },
                        new
                        {
                            BookId = 12,
                            AuthorId = 4
                        });
                });

            modelBuilder.Entity("LibraryApi.Models.BookCategory", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 5,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 5,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 6,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 6,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 7,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 7,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 8,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 9,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 10,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 11,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 12,
                            CategoryId = 3
                        });
                });

            modelBuilder.Entity("LibraryApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Literary works created from the imagination",
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fiction dealing with futuristic science and technology",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Non-fiction works about past events",
                            Name = "History"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Non-fiction works about the natural world",
                            Name = "Science"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Non-fiction accounts of a person's life",
                            Name = "Biography"
                        });
                });

            modelBuilder.Entity("LibraryApi.Models.Fine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatronId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.HasIndex("PatronId");

                    b.ToTable("Fines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1.50m,
                            CreatedAt = new DateTime(2025, 3, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IssuedDate = new DateTime(2025, 3, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            LoanId = 5,
                            PatronId = 2,
                            Reason = "Overdue: 6 days late",
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 0.75m,
                            CreatedAt = new DateTime(2025, 3, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IssuedDate = new DateTime(2025, 3, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            LoanId = 7,
                            PatronId = 6,
                            Reason = "Overdue: 3 days late",
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 0.50m,
                            CreatedAt = new DateTime(2025, 2, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            IssuedDate = new DateTime(2025, 2, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            LoanId = 4,
                            PaidDate = new DateTime(2025, 2, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            PatronId = 1,
                            Reason = "Overdue: 2 days late",
                            Status = "Paid"
                        });
                });

            modelBuilder.Entity("LibraryApi.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatronId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RenewalCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("PatronId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 2,
                            CreatedAt = new DateTime(2025, 3, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 3, 31, 10, 0, 0, 0, DateTimeKind.Utc),
                            LoanDate = new DateTime(2025, 3, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            PatronId = 1,
                            RenewalCount = 0,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 4,
                            CreatedAt = new DateTime(2025, 3, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 3, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            LoanDate = new DateTime(2025, 3, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            PatronId = 2,
                            RenewalCount = 0,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            BookId = 6,
                            CreatedAt = new DateTime(2025, 3, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 3, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            LoanDate = new DateTime(2025, 3, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            PatronId = 3,
                            RenewalCount = 0,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            BookId = 9,
                            CreatedAt = new DateTime(2025, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 2, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            LoanDate = new DateTime(2025, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            PatronId = 1,
                            RenewalCount = 0,
                            ReturnDate = new DateTime(2025, 2, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Returned"
                        },
                        new
                        {
                            Id = 5,
                            BookId = 1,
                            CreatedAt = new DateTime(2025, 2, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 3, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            LoanDate = new DateTime(2025, 2, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            PatronId = 2,
                            RenewalCount = 0,
                            Status = "Overdue"
                        },
                        new
                        {
                            Id = 6,
                            BookId = 5,
                            CreatedAt = new DateTime(2025, 3, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 3, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            LoanDate = new DateTime(2025, 3, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            PatronId = 4,
                            RenewalCount = 0,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 7,
                            BookId = 3,
                            CreatedAt = new DateTime(2025, 3, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 3, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            LoanDate = new DateTime(2025, 3, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            PatronId = 6,
                            RenewalCount = 0,
                            Status = "Overdue"
                        },
                        new
                        {
                            Id = 8,
                            BookId = 7,
                            CreatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 2, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            LoanDate = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            PatronId = 1,
                            RenewalCount = 0,
                            ReturnDate = new DateTime(2025, 2, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Returned"
                        });
                });

            modelBuilder.Entity("LibraryApi.Models.Patron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("MembershipDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Patrons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Oak Street",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice.johnson@email.com",
                            FirstName = "Alice",
                            IsActive = true,
                            LastName = "Johnson",
                            MembershipDate = new DateOnly(2023, 6, 15),
                            MembershipType = "Premium",
                            Phone = "555-0101",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm Avenue",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob.smith@email.com",
                            FirstName = "Bob",
                            IsActive = true,
                            LastName = "Smith",
                            MembershipDate = new DateOnly(2024, 1, 10),
                            MembershipType = "Standard",
                            Phone = "555-0102",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine Road",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carol.williams@email.com",
                            FirstName = "Carol",
                            IsActive = true,
                            LastName = "Williams",
                            MembershipDate = new DateOnly(2024, 9, 1),
                            MembershipType = "Student",
                            Phone = "555-0103",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Maple Drive",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david.brown@email.com",
                            FirstName = "David",
                            IsActive = true,
                            LastName = "Brown",
                            MembershipDate = new DateOnly(2024, 3, 20),
                            MembershipType = "Standard",
                            Phone = "555-0104",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Address = "654 Cedar Lane",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "eve.davis@email.com",
                            FirstName = "Eve",
                            IsActive = false,
                            LastName = "Davis",
                            MembershipDate = new DateOnly(2023, 11, 5),
                            MembershipType = "Premium",
                            Phone = "555-0105",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Address = "987 Birch Court",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "frank.wilson@email.com",
                            FirstName = "Frank",
                            IsActive = true,
                            LastName = "Wilson",
                            MembershipDate = new DateOnly(2024, 8, 15),
                            MembershipType = "Student",
                            Phone = "555-0106",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LibraryApi.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatronId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueuePosition")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("PatronId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            CreatedAt = new DateTime(2025, 3, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            PatronId = 4,
                            QueuePosition = 1,
                            ReservationDate = new DateTime(2025, 3, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 3,
                            CreatedAt = new DateTime(2025, 3, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            PatronId = 3,
                            QueuePosition = 1,
                            ReservationDate = new DateTime(2025, 3, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            BookId = 5,
                            CreatedAt = new DateTime(2025, 3, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            ExpirationDate = new DateTime(2025, 3, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            PatronId = 1,
                            QueuePosition = 1,
                            ReservationDate = new DateTime(2025, 3, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Ready"
                        });
                });

            modelBuilder.Entity("LibraryApi.Models.BookAuthor", b =>
                {
                    b.HasOne("LibraryApi.Models.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryApi.Models.BookCategory", b =>
                {
                    b.HasOne("LibraryApi.Models.Book", "Book")
                        .WithMany("BookCategories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.Category", "Category")
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryApi.Models.Fine", b =>
                {
                    b.HasOne("LibraryApi.Models.Loan", "Loan")
                        .WithMany("Fines")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.Patron", "Patron")
                        .WithMany("Fines")
                        .HasForeignKey("PatronId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loan");

                    b.Navigation("Patron");
                });

            modelBuilder.Entity("LibraryApi.Models.Loan", b =>
                {
                    b.HasOne("LibraryApi.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.Patron", "Patron")
                        .WithMany("Loans")
                        .HasForeignKey("PatronId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Patron");
                });

            modelBuilder.Entity("LibraryApi.Models.Reservation", b =>
                {
                    b.HasOne("LibraryApi.Models.Book", "Book")
                        .WithMany("Reservations")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.Patron", "Patron")
                        .WithMany("Reservations")
                        .HasForeignKey("PatronId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Patron");
                });

            modelBuilder.Entity("LibraryApi.Models.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("LibraryApi.Models.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("BookCategories");

                    b.Navigation("Loans");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("LibraryApi.Models.Category", b =>
                {
                    b.Navigation("BookCategories");
                });

            modelBuilder.Entity("LibraryApi.Models.Loan", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("LibraryApi.Models.Patron", b =>
                {
                    b.Navigation("Fines");

                    b.Navigation("Loans");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
